GENE_NAMES = [
    "BRCA1", "TP53", "EGFR", "VEGFA", "APOE", "IL6", "MTHFR", "TNF",
    "ESR1", "AKT1", "MTOR", "KRAS", "CDKN2A", "PTEN", "RB1", "GATA3",
    "MAPK1", "MAPK3", "HRAS", "CCND1", "MYC", "JAK2", "ABL1", "PDGFRA",
    "ERBB2", "NOTCH1", "SMAD4", "TGFBR1", "CDK4", "FLT3", "KIT", "MET",
    "NTRK1", "NTRK2", "NTRK3", "BRAF", "ALK", "ROS1", "RET"
]


"""
(generated by chatGPT)
The list of gene names provided includes some of the most well-known and commonly studied genes in human genetics and biomedical research. These genes are frequently involved in important biological processes, and many of them are linked to various diseases, including cancers, genetic disorders, and other medical conditions. Here’s a brief overview of why these particular genes are notable:

BRCA1, BRCA2: Tumor suppressor genes involved in breast and ovarian cancer risk.
TP53: Tumor suppressor gene often mutated in various cancers.
EGFR: Gene encoding the epidermal growth factor receptor, involved in cell growth and differentiation; often mutated in cancers.
VEGFA: Gene involved in angiogenesis (formation of blood vessels); targeted in cancer therapy.
APOE: Gene associated with Alzheimer's disease risk.
IL6: Cytokine gene involved in inflammation and immune response.
MTHFR: Gene involved in folate metabolism; mutations can affect cardiovascular health and pregnancy.
TNF: Tumor necrosis factor; involved in inflammation and immune system regulation.
ESR1: Estrogen receptor gene, important in breast cancer.
AKT1, MTOR: Genes involved in cell growth, proliferation, and survival pathways.
KRAS: Oncogene frequently mutated in cancers.
CDKN2A, PTEN, RB1: Tumor suppressor genes involved in cell cycle regulation.
GATA3: Transcription factor important in immune system and breast cancer.
MAPK1, MAPK3: Genes involved in the MAP kinase signaling pathway, important in cell proliferation and differentiation.
HRAS: Oncogene involved in cell signaling.
CCND1: Cyclin D1 gene involved in cell cycle regulation.
MYC: Oncogene involved in cell cycle progression, apoptosis, and cellular transformation.
JAK2: Gene involved in cytokine signaling; mutations are common in blood cancers.
ABL1: Gene involved in cell differentiation and division; the BCR-ABL fusion gene is characteristic of chronic myeloid leukemia.
PDGFRA: Gene involved in cell growth and division; mutations can cause cancers.
ERBB2 (HER2): Gene involved in cell growth and differentiation; amplified in some breast cancers.
NOTCH1: Gene involved in cell differentiation; mutations found in various cancers.
SMAD4: Tumor suppressor gene involved in TGF-beta signaling pathway.
TGFBR1: Gene involved in TGF-beta signaling pathway; mutations linked to cancer.
CDK4: Gene involved in cell cycle regulation.
FLT3: Gene involved in blood cell development; mutations common in acute myeloid leukemia.
KIT: Gene involved in cell survival and proliferation; mutations found in gastrointestinal stromal tumors.
MET: Oncogene involved in cell growth and differentiation.
NTRK1, NTRK2, NTRK3: Genes encoding neurotrophic receptors; fusions linked to various cancers.
BRAF: Gene involved in cell growth; mutations common in melanoma.
ALK: Oncogene involved in cell growth; mutations and fusions found in various cancers.
ROS1: Oncogene involved in cell growth; fusions found in some cancers.
RET: Oncogene involved in cell growth; mutations linked to multiple endocrine neoplasia and medullary thyroid cancer.

These names were selected based on their relevance in scientific research and medicine. However, for a more diverse set of gene names, you can refer to resources such as:

The Human Genome Organization (HUGO) Gene Nomenclature Committee (HGNC): HGNC Database
National Center for Biotechnology Information (NCBI) Gene Database: NCBI Gene
Ensembl Genome Browser: Ensembl Genes
"""
